# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macOS-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run test
        run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,name=iPhone 8' test

      # Runs a set of commands using the runners shell
      - name: Build App
        run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
     
